# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRF3Vay4e__HzcMnYXNPd4Eyd0SR0PjH
"""

import torch
import torch.nn as nn
import torchvision.models as models
import torch.nn.functional as F

# ResNet18 modeli
class resnet(nn.Module):
    def __init__(self):
        super(resnet, self).__init__()
        temp = models.resnet18(pretrained=True)  # Önceden eğitilmiş model
        num_ftrs = temp.fc.in_features
        temp.fc = nn.Linear(num_ftrs, 20)  # Son katmanı değiştir
        model_ft = temp.to("cuda:0")  # GPU'ya taşı
        self.model = model_ft

    def forward(self, x):
        x = self.model(x)
        return x

# VGG16 modeli
class vgg(nn.Module):
    def __init__(self):
        super(vgg, self).__init__()
        temp = models.vgg16_bn(pretrained=True)  # Önceden eğitilmiş model

        temp.classifier[6] = nn.Linear(4096, 20)  # Son katmanı değiştir

        # Son katmanın ağırlıklarını eğitilebilir yap
        temp.classifier[6].weight.requires_grad = True
        temp.classifier[6].bias.requires_grad = True

        model_ft = temp.to("cuda:0")  # GPU'ya taşı
        self.model = model_ft

    def forward(self, x):
        x = self.model(x)
        return x

# Model seçimi için fonksiyon (daha sonra doldurulacak)
def get_model(args):
    model = None
    return model

